### ISSUE TITLE
Customize code for billing and shipping address

### ISSUE THREAD

**Issue by msyahrizan** [woocommerce/woocommerce-gutenberg-products-block#11936]
Hi, I'm using the following code to hide my second address and make the phone field required:

`<!-- wp:woocommerce/checkout {"showApartmentField":false,"requirePhoneField":true}  -->`

I have a couple of questions:

1. What is the code name for the Last Name field? I want to set it to false.
2. How can I arrange the form to make it wider or change the order of the fields? For example, I want to make the First Name field wider, place the Zip Code in the first row, and make City the last row. I want to design my own address form within my checkout block.

Example:
First Name (wide)
Zip Code (first row) / City (last row)

3. How can I arrange it to have the Phone field come before the Name field?

I know how to achieve these customizations on the normal WooCommerce Checkout page, but I'm unsure how to do it with Blocks.

Thank you.

**Comment by senadir** [comment]
Hello! that code only applies to the phone, address, and company fields.

For the rest, field visibility and placement depend a lot on the selected country, so you can't make wide changes but you can make changes to specific countries using `woocommerce_get_country_locale` filter, for example, changing that for the US would be like:

```php
add_filter(
	'woocommerce_get_country_locale',
	function ( $locale ) {
		$locale['US']['phone'] = array(
			'required' => true,
			'hidden' => false,
			'priority' => 1,
		);

		$locale['US']['postcode'] = array(
			'required' => true,
			'hidden' => false,
			'priority' => 10,
		);

		$locale['US']['last_name'] = array(
			'required' => false,
			'hidden' => true,
		);

		$locale['US']['city'] = array(
			'required' => true,
			'hidden' => false,
			'priority' => 100,
		);

		return $locale;
	}
);
```

When it comes to making a field wide, you will need to use CSS for now:

```css
.is-large .wc-block-checkout__billing-fields .wc-block-components-address-form .wc-block-components-address-form__first_name,
.is-large .wc-block-checkout__shipping-fields .wc-block-components-address-form .wc-block-components-address-form__first_name,
.is-medium .wc-block-checkout__billing-fields .wc-block-components-address-form .wc-block-components-address-form__first_name,
.is-medium .wc-block-checkout__shipping-fields .wc-block-components-address-form .wc-block-components-address-form__first_name,
.is-small .wc-block-checkout__billing-fields .wc-block-components-address-form .wc-block-components-address-form__first_name,
.is-small .wc-block-checkout__shipping-fields .wc-block-components-address-form .wc-block-components-address-form__first_name {
	flex: 0 0 100%;
}
```
