### ISSUE TITLE
Inconsistent "Filter by x" block title background in 2020 theme

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#1204]
**Describe the bug**
The "Filter by attributes" and "Filter by price" blocks have inconsistent backgrounds in the title, in the editor, the title has a white background, in the fronted, it has no background.

**Expected behavior**
It should have no background in the editor, or a background at the frontend, but not both at the same time.

**Screenshots**

Editor:

<img width="677" alt="Screen Shot 2019-11-19 at 9 25 45 AM" src="https://user-images.githubusercontent.com/6165348/69131248-508b8a00-0ab2-11ea-8567-b08dcc9a38d3.png">

Theme:

<img width="680" alt="Screen Shot 2019-11-19 at 9 25 57 AM" src="https://user-images.githubusercontent.com/6165348/69131250-51242080-0ab2-11ea-8266-be13a245caf3.png">

**How to fix**
The title in the editor is a textarea, `forms.css` seems to hardcode background colors for inputs to white, we can override it to transparent for our blocks, fixing the issue

**Code that causes the problem**
```css
textarea {
    background-color: #fff;
}
``` 

**The fix**

```css
.wc-block-attribute-filter-heading {
    background-color: transparent:
}
```
