### ISSUE TITLE
Latest Update 21.01.2021 Radio Buttons Colors

### ISSUE THREAD

**Issue by endreb8** [woocommerce/woocommerce-gutenberg-products-block#3715]
In the latest update something changed in the colors handling of radio buttons.
But still there are issues not solved due to the wrong colors inherit from the theme.

Basically for Astra Pro theme there is a problem with colors inhering because border-color and background-color inherits wrong colors from the theme, making the buttons look bad.

Also with the new update, can not set anymore the color of the selected option.

To come around to this issue it is necessary for unset with additional css.

border-color: unset !important;
background-color: unset !important;

I would strongly suggest to allow users to optionally set the colors manually without inheriting from the theme.

Thanks in advance,

**Comment by nerrad** [comment]
Hi @endreb8 could you share some screenshots so we can make sure we're clear on what specific radio buttons you are referring to? Thanks!

**Comment by endreb8** [comment]
> Hi @endreb8 could you share some screenshots so we can make sure we're clear on what specific radio buttons you are referring to? Thanks!

Hi @nerrad , thanks for your reply.

Please find attached screenshot of how buttons inherits the theme colors when no additional css is present to unset.

![buttons](https://user-images.githubusercontent.com/77777753/105629667-1a336280-5e4d-11eb-8c92-c9975897e767.jpg)

And the following is the css to unset and fix the above issue:

![css](https://user-images.githubusercontent.com/77777753/105629679-2cad9c00-5e4d-11eb-885e-466ade8b1511.jpg)

The following is the normal result let's say :)

![normal](https://user-images.githubusercontent.com/77777753/105629723-6383b200-5e4d-11eb-9d02-89e37d4b408a.jpg)

Although I would prefer red border and red selection color but after the last update can not change anymore the color of the selected (the black dot "color:" does not work anymore.)

Thanks in advance,

**Comment by budzanowski** [comment]
Hi @endreb8:
> Although I would prefer red border and red selection color but after the last update can not change anymore the color of the selected (the black dot "color:" does not work anymore.)

This is the CSS that can be used to customize the Radio buttons:
```CSS
.wc-block-components-radio-control .wc-block-components-radio-control__input {
    background-color: white;
    border-color: red;
}

.wc-block-components-radio-control .wc-block-components-radio-control__input:checked:before {
    background: red;
}
```

Such setup results in the following appearance:
![image](https://user-images.githubusercontent.com/17271089/105687589-eb72c600-5ef8-11eb-8f85-fbb40a6dee4d.png)

**Comment by budzanowski** [comment]
Hi @endreb8 

There were recent changes that are targetting better visibility for dark backgrounds. This causes a small conflict with how the Astra theme is styling the inputs. The full solution is to contact developers of the theme because they will need to account for the new CSS that the plugin provides. Bellow, is a workaround CSS solution that you can use to eliminate the problem and style the :

> Although I would prefer red border and red selection color but after the last update can not change anymore the color of the selected (the black dot "color:" does not work anymore.)

```CSS
.wc-block-components-radio-control .wc-block-components-radio-control__input,
.wc-block-components-radio-control .wc-block-components-radio-control__input:checked {
    background-color: white;
    border-color: red;
}

.wc-block-components-radio-control .wc-block-components-radio-control__input:checked:before {
    background: red;
}

```

This has the following effects:
![image](https://user-images.githubusercontent.com/17271089/105690870-ced88d00-5efc-11eb-91b7-05315408e852.png)

I hope that this helps!
