### ISSUE TITLE
Featured Category Block: Buttons have .aligncenter class but are left aligned

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#3788]
I tested this in 2019 theme using the defaults on the Featured Category Block:

![Screenshot 2021-02-04 at 13 24 23](https://user-images.githubusercontent.com/90977/106898784-85522400-66ec-11eb-928f-6308b018653c.png)

I can see the button has the correct aligncenter class, but the parent element has width:100% which forces left alignment. This only appears to affect the frontend of the store.

**Comment by ralucaStan** [comment]
Seems to be the case as well for Featured Product. From what I could tell, this class is missing:

```css
.wp-block-button.aligncenter, .wp-block-buttons.aligncenter, .wp-block-calendar {
    text-align: center;
}
```
