### ISSUE TITLE
Botton color

### ISSUE THREAD

**Issue by Fabiovisualdesign** [woocommerce/woocommerce-gutenberg-products-block#3916]
How to change the button color in woocommerce block in the shopping cart? What kind of css?

**Comment by senadir** [comment]
You can use this CSS
```css
.components-button.wc-block-components-button.wc-block-cart__submit-button {
    background-color: white;
}
```
