### ISSUE TITLE
Limit CSS styles to WooCommerce Block icons only

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-gutenberg-products-block#5355]
## Describe the bug

In https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5317, I added the following CSS definition that ensures that the icon remains readable when being selected in the list view:

```css
// Display white icon when block is selected in list view.
.block-editor-list-view-leaf.is-selected {
	.block-editor-list-view-block-contents {
		svg {
			fill: #fff;
		}
	}
}
```

In https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5317#discussion_r765857807, @Aljullu pointed out that this CSS definition should only affect the icons of the WooCommerce Blocks plugin. In addition, he suggested using `currentColor` instead of `#fff`.

## To reproduce

1. Create a test page.
2. Add one block to the page, that comes from the WooCommerce Blocks plugin.
3. Add one block to the page, that does not come from the WooCommerce Blocks plugin.
4. Open the list view.
5. Select the block that comes from the WooCommerce Blocks plugin.
6. Verify that the icon color, when the block is selected, comes from the the WooCommerce Blocks plugin.
7. Select the block that does not come from the WooCommerce Blocks plugin.
8. Verify that the icon color, when the block is selected, also comes from the the WooCommerce Blocks plugin.

## Expected behavior

The CSS definition for the icon should only affect blocks of the WooCommerce Blocks plugin.
