### ISSUE TITLE
Product categories block targeting category name needs an html tag for CSS targeting

### ISSUE THREAD

**Issue by Pagester** [woocommerce/woocommerce-gutenberg-products-block#6571]
## Is your feature request related to a problem? Please describe.

Line 325 of file ["woo-gutenberg-products-block/src/BlockTypes/ProductCategories.php"](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/ProductCategories.php)

The actual category name is missing an html tag, a `<span>` or `<p>` tag so that the name can be targeted for CSS.

Without a tag around the name its an anonymous box. So for example you cannot apply `text-overflow:ellipsis` as within the `a href ` tag there is a `<span>` for the image. This causes problems for overflow styling of long category names and responsive styling issues.

## Describe the solution you'd like
Add a span tag and css class to `esc_html( $category->name )` on line 325 to allow more refined targeting of text more appropiately.

Replace line 325 with this amended line

`<a style="' . esc_attr( $link_color_style ) . '" href="' . esc_attr( get_term_link( $category->term_id, 'product_cat' ) ) . '">' . $this->get_image_html( $category, $attributes ) . '<span class="wc-block-product-categories-list-item__title">' . esc_html( $category->name ) . '</span>' . '</a>`

## Additional context

Not sure if this is a bug so I'm submitting as a feature request. 

Making this change would assist greatly in being able to move more sites from page builders to Gutenberg. The more elements can be targeted with custom CSS the less requirement for a page builder.

**Comment by tomasztunik** [comment]
I've checked and this fix doesn't invalidate the block. Going to name the class with `__name` suffix to align it with the attribute name. Getting it to work will require Introducing some extra CSS on the text wrapper and parent elements. With horizontal flex on the list and anchor elements.

Going to contribute a patch, should go live with the next release.

Minimal changes I found were 

```css
.wc-block-product-categories-list-item {
    display: flex;
    align-items: center;
}

.wc-block-product-categories-list-item a {
    display: flex;
    align-items: center;
    max-width: 100%;
}

.wc-block-product-categories-list-item__name {
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
}
```
